name: Docker build and push sd app

on:
  push:
    paths:
      - "sd/**"
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build-sd-service:
    uses: dkr290/devops-projects/.github/workflows/docker-build-template.yml@main
    with:
      name: Build and push sd image generator docker image
      docker_image_name: ghcr.io/${{ github.repository }}/sd
      version: "1.0.4"
      folder: sd
      dockerfileName: sd/Dockerfile
