name: Docker build and push wan2GP app

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-wan2gp:
    uses: dkr290/devops-projects/.github/workflows/docker-build-push.yml@main
    with:
      name: Build and push swarmUI
      docker_image_name: ghcr.io/${{ github.repository }}/swarm-ui
      version: "runpod-swarmui-1.0.1"
      folder: swarmui
      dockerfileName: Dockerfile
