name: Docker build and push swarmUI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-swarmUI:
    uses: dkr290/devops-projects/.github/workflows/docker-build-push.yml@main
    with:
      name: Build and push swarmUI
      docker_image_name: ghcr.io/${{ github.repository }}/swarm-ui
      version: "runpod-swarmui-1.0.2"
      folder: swarmui/swarmui
      dockerfileName: Dockerfile

  build-swarmUI-packed:
    uses: dkr290/devops-projects/.github/workflows/docker-build-push.yml@main
    with:
      name: Build and push swarmUI-Comfy
      docker_image_name: ghcr.io/${{ github.repository }}/swarm-ui-compfy
      version: "runpod-swarmui-1.0.3"
      folder: swarmui/swarmui-buildin
      dockerfileName: Dockerfile
