name: Docker build and push wan2GP app

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-ampere:
    uses: dkr290/devops-projects/.github/workflows/docker-build-push.yml@main
    with:
      name: Build and push  rtx3xx ampere wan2gp
      docker_image_name: ghcr.io/${{ github.repository }}/wan2gp
      version: "rtx3x-ampere.0.2"
      folder: wan2gp
      dockerfileName: rtx3x-Ax-86.dockerfile

  build-ada:
    uses: dkr290/devops-projects/.github/workflows/docker-build-push.yml@main
    needs: build-ampere
    with:
      name: Build and push rtx4xx ada
      docker_image_name: ghcr.io/${{ github.repository }}/wan2gp
      version: "rtx4x-ada.0.2"
      folder: wan2gp
      dockerfileName: rtx4x-lx-89.dockerfile

  build-blackwell:
    uses: dkr290/devops-projects/.github/workflows/docker-build-push.yml@main
    needs: build-ada
    with:
      name: Build and push blackwell
      docker_image_name: ghcr.io/${{ github.repository }}/wan2gp
      version: "rtx4x-blackwell.0.2"
      folder: wan2gp
      dockerfileName: rtx5x-Ax-90.dockerfile
