name: Docker build and push wan2GP app

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-api-service:
    uses: dkr290/.github/workflows/docker-build-push.yml@main
    with:
      name: Build and push go-ai-gen image generator docker image
      docker_image_name: ghcr.io/${{ github.repository }}/wan2gp
      version: "1.0.0"
      folder: .
      dockerfileName: Dockerfile
