name: Docker build and push wan2GP app

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-wan2gp:
    uses: dkr290/devops-projects/.github/workflows/docker-build-push.yml@main
    with:
      name: Build and push wan2gp
      docker_image_name: ghcr.io/${{ github.repository }}/wan2gp
      version: "runpod-nonflash-1.0.90"
      folder: wan2gp/runpod
      dockerfileName: Dockerfile
